services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/usr/src/app/database  # Solo la BD persistente
    environment:
      - NODE_ENV=development
    command: npm start

volumes:
  sqlite_data: